feat: advancedNetwork, interceptors, standalone
smartlook/smartlook-client pull request #33
Opened 2023-02-28 00:39 UTC by millcek

2023-02-28 08:36 UTC, Joozty commented on index.ts
> +	// Advanced network recording allows recording the bodies and headers of requests and responses.
these descriptions should go to README.md as well... ideally add there also links to appropriate pages to our docs.

2023-02-28 09:29 UTC, amertak requested changes
Nahod to prosim do toho readme.md jeste

Upravim to v readme.com to cele smartlook init volani o ty chybejici parametry

2023-02-28 09:29 UTC, amertak commented on index.ts
> +	) => void | boolean
void | false

2023-03-01 06:30 UTC, Joozty approved these changes
👍

2023-03-01 07:38 UTC, Joozty commented
Actually I just noticed, you forgot to update init params 

https://github.com/smartlook/smartlook-client/blob/feat/advancedNetwork%2C-interceptors%2C-standalone/index.ts#L66

2023-03-01 07:59 UTC, Joozty commented on index.ts
> +type InitParams = {
this and maybe above interface as well coudl get exported so customer can use it like this:

```ts
const interceptors: Interceptors = ...
const config: InitParams = {..., interceptors}
smartlook.init('key', config)
```

what do you think @smartlook/web-sdk?

2023-03-01 10:06 UTC, millcek commented
pushed to master directly

2023-03-01 10:06 UTC, closed without merging